### ISSUE TITLE
[1.18.2 & 1.19] Crash when clicking PLAYERS in Entity list dropdown.

### ISSUE THREAD

**Issue by Gbergz** [Darkere/CrashUtilities#26]
Title^

Crash found in 1.18.2 & 1.19

**Versions:**
Forge: 41.0.48 & 40.1.48
Minecraft: 1.18.2 & 1.19
Crash Utils: 4.1 & 5.0

**Crash-Report**: https://gist.github.com/Gbergz/fe4db148456cd2cad3ed916521b6662f

**-** Gbergz

**Comment by Darkere** [comment]
This on server or client?
Code is telling me "this cannot happen" :/

**Comment by Darkere** [comment]
Either fixed in 1.19.1 or some other mod is messing with the player list

**Comment by Gbergz** [comment]
Pretty sure this was on a server!

> Either fixed in 1.19.1 or some other mod is messing with the player list

Gotcha!

**Comment by Sora-Canstavia** [comment]
I know this is marked as closed, but just wanted to put out there that I've been having this issue myself, and have been doing some testing on my end, ended up removing all of the mods except for Crash Utilities and this still persisted.

For me, the Forge versions I tested on was: 40.1.17 and 40.1.68
Minecraft version: 1.18.2
Crash Utilities version: 4.1

My own crash report: https://paste.ee/p/yg4Ya

To note, I could only replicate this when accessing the player list on a server, it worked fine in singleplayer.

**Comment by CKY-** [comment]
I know this is marked as closed, but just wanted to put out there it's still crashing I know you said fixed in 1.19.1 but thats 1.19.1 and not 1.18.2 

For me, the Forge versions I tested on was: 40.1.17 and 40.1.68
Minecraft version: 1.18.2
Crash Utilities version: 4.1
here is a better ish crash log that may help 
https://crashy.net/qakg9ygx0ahetbUxit1V
This is server side 
a relog  shows the players list just fine.

**Comment by izybel** [comment]
HI there i know this is marked as closed but I'm currently on a server that is using the 1.18.2 version and am having this issue as well it would be really awesome if it were fixed in the 1.18.2 version

This is my crash log if its any help to be able to understand the issue better 
https://bytebin.lucko.me/5V4ocl3Sw7

thanks in advance, 
Izybel_
